# Generated by Django 3.0.7 on 2020-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_displayer', '0005_auto_20200616_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
